### ISSUE TITLE
Using gem compiler in a restricted server environment

### ISSUE THREAD

**Issue by rgiessmann** [luislavena/gem-compiler#39]
Hi Luis,

I am aiming to have a production machine running a Ruby on Rails app. However, this production machine is managed with Plesk and allows only very rudimentary access, but was promised to be able to run Ruby on Rails apps.

Indeed it is in principle able to run Ruby on rails for an very simple example, but running any app requiring gems with native extensions (as e.g. nokogiri, which is required already by the rails default app, generated by rails new) already fails.

Part of the log looks like this:

```
libruby.so.2.4: cannot open shared object file: No such file or directory - /var/www/vhosts/hosting116285.a2f45.netcup.net/test.gcsb.info/vendor/bundle/ruby/2.4.0/gems/msgpack-1.2.6-x86_64-linux/lib/msgpack/msgpack.so (LoadError)
/var/www/vhosts/hosting116285.a2f45.netcup.net/test.gcsb.info/vendor/bundle/ruby/2.4.0/gems/msgpack-1.2.6-x86_64-linux/lib/msgpack.rb:11:in `require'
...
...
...
/var/www/vhosts/hosting116285.a2f45.netcup.net/test.gcsb.info/vendor/bundle/ruby/2.4.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `initialize'
config.ru:1:in `new'
config.ru:1:in `<main>'
/usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `eval'
/usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `preload_app'
/usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
/usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
/usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
```

I have the options to "restart the app", "install packages" (which executes a bundle install --path vendor/bundle according to documentation), and "add environment variables".

I have very limited SSH access to the machine, but no access to any compilers or libraries.

The support advised me to "precompile my gems", but did not give any specific advice how to do this. I set up a virtual development machine which is somewhat near to the production machine, but definitely not yet the same in terms of all paths and e.g. Linux kernel version. I compiled the gems which supposedly works fine, put the precompiled gems in <code>vendor/cache</code> on the server, and install them via the Plesk interface.

However, the app keeps throwing errors. The pre-compiled gems (msgpack is one of them; originally with native extensions) seem to be linked in a wrong fashion? Maybe it's the linkage to ruby that it broken? I read about another (closed) issue where this linking is referenced?

Do you have an idea on this, or could you provide me with a "this is how we usually do it"-strategy? Do you intended gem-compiler to work for such a scenario, or am I misled? (If so, maybe we can update the Readme together?) 

Thanks in advance! -- Robert

**Comment by luislavena** [comment]
Hello @rgiessmann, apologies for the delayed response. I thought left a comment when assigning the  `question` label, but seems forgot to submit 🤦‍♂️ 

> Do you intended gem-compiler to work for such a scenario, or am I misled?

Yes and no. gem-compiler was created to work to remove the need of having a compiler available on the final machines, but you need to have certain control on OS or the version of Ruby. In your case, you have none of the later, so aiming to produce a 100% reproducible environment might be a challenge.

> Do you have an idea on this, or could you provide me with a "this is how we usually do it"-strategy?

My recommendation on this will be a deeper analysis of the Ruby installation they provide and be able to mimic as much as possible their options.

If `libruby.so.2.4` is failing to load `msgpack.so`, it might linking to other shared objects that might be missing on the target platform.

I will recommend mimic as much as possible the exact version of Ruby that is installed in the remote, including the build options.

Given the limited SSH access you have, try to use the following commands:

Obtain the configure options that were used to build Ruby:

```console
$ ruby -v -e 'puts RbConfig::CONFIG["configure_args"]'
```

This should provide you the options to be used when building your version of Ruby in your copy of the environment. Options like `--enable-shared` and `--enable-load-relative` have an important role when trying to load extensions that were produced by a non-similar environment.

Try to use the same options when compiling the version of Ruby you're using to generate the binary gems.

Also, try to determine the versions/libraries `libruby.so.2.4` links to, and confirm the ones of `msgpack.so` too, using `ldd` (if available)

```console
$ ldd /var/www/vhosts/hosting116285.a2f45.netcup.net/test.gcsb.info/vendor/bundle/ruby/2.4.0/gems/msgpack-1.2.6-x86_64-linux/lib/msgpack/msgpack.so

$ ldd /path/to/libruby.so.2.4
```

Since I don't know more details of your ruby installation, check if `configure_args` showed a `--prefix` option and inspect a relative `lib` directory that might include the respective `.so` file.

You might also look for `libruby.so.2.4` by using `ldd` over the `ruby` interpreter in use. Use `which ruby` to determine the location and then use `ldd` on it, example:

```console
$ ldd ~/.asdf/installs/ruby/2.5.1/bin/ruby
        linux-vdso.so.1 =>  (0x00007fffeda03000)
        libruby.so.2.5 => /home/luis/.asdf/installs/ruby/2.5.1/bin/../lib/libruby.so.2.5 (0x00007f41b62f4000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f41b5f20000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f41b5d00000)
        libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f41b5a70000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f41b5860000)
        libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f41b5620000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f41b5300000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f41b6a00000)
```

Let me know if these help you.

Cheers.

**Comment by luislavena** [comment]
Hello @rgiessmann, didn't receive a follow up from your end.

Please let me know if you're still interested into explore this or have additional questions.

Cheers.

**Comment by luislavena** [comment]
Hello @rgiessmann, doing a follow up on this. Are you still experiencing this issue? Were you able to explore my previous comments?

Please let me know.

Cheers.

**Comment by luislavena** [comment]
Hello @rgiessmann, closing this due inactivity.

Please let us know if you're still impacted by this and can provide more details.

Cheers.
