### ISSUE TITLE
Benchmarks?

### ISSUE THREAD

**Issue by MatheusRich** [luislavena/gem-compiler#42]
Do you have any benchmark to show how does this improves build time?

**Comment by luislavena** [comment]
Hello @MatheusRich, thanks for your interest and making a really great question!

I was able to reduce deployment of a Rails application to Heroku from almost 4 minutes for a new version to 3 seconds by having nokogiri and puma pre-compiled.

Of course that subsequent pushes to Heroku will reuse Bundler cache, but new version of nokogiri will slow you down again.

I don't have this week to work on the project but will add some details in the upcoming weeks.

Hope this initial information helps you and let me know otherwise.

**Comment by MatheusRich** [comment]
@luislavena Yeah, that's great! I've watched your talk at RubyParis 2018 on Youtube. I opened this issue 'cause I thought it would be cool to have these numbers on README.

**Comment by luislavena** [comment]
Hello @MatheusRich, thanks for your patience.

I've added benchmark information for a single gem to the README. Not going to describe specific Rails cases, but it should be enough.

Cheers!
