### ISSUE TITLE
Uploading multiple versions of ABI to rubygems

### ISSUE THREAD

**Issue by avsej** [luislavena/gem-compiler#56]
Hi Luis, 

My question probably not related to gem-compiler in particular. What if I've built two versions of binary gem for the same platform (say `x86_64-linux`). One with ABI `2.7` and another with `2.6`. When I upload one of them to rubygems, it does not allow me to upload another complaining about republishing. 

But when I later try to install without `--platform=ruby` it by default download binary version regardless the ABI I'm using right now.

So the actual question is, how to resolve this problem? Is it even possible to have separate packages on rubygems that compiled against different ABI? I can see it in gem's metadata, then why it does not use this information during install and does not allow to upload multiple versions of binaries.

**Comment by luislavena** [comment]
Hello @avsej, thanks for your question. While not directly connected to gem-compiler, these are indeed interesting!

The inability to push two different gems to rubygems.org is a limitation of RubyGems and rubygems.org by omission. While RubyGems uses `version` and `platform` information to construct a unique key for a gem, is actually ignoring `ruby_version` that could indicate an ABI compatibility (please note that `ruby_version` of a gem is still used during gem installation).

What you're describing is something that has been discussed since 2009 and that Aaron Patterson explained in his blog [here](https://tenderlovemaking.com/2009/05/07/fat-binary-gems-make-the-rockin-world-go-round.html). While talking about Ruby 1.8 and 1.9 and Windows, these issues still applies to RubyGems today, independently of the platform you're targeting.

It would be great if RubyGems and rubygems.org addressed those issues and use Ruby's ABI information to help construct that key information, but not sure the impact it will have on rubygems.org infrastructure, data and API.

Binary gems on Windows are mostly OK, simply because there is one binary distribution (RubyInstaller), but on Linux, there are many different ways to install Ruby that possible binaries generated in one Linux platform might not work on others.

Take as example #51: Ruby installed with RVM might cause a gem compiled for a version (still ABI compatible) might not work with another ABI compatible one). (_thinking out loud_) perhaps that could be workaround by compiling Ruby with `--enable-load-relative`, something I shared back in 2012 in #1 

> But when I later try to install without `--platform=ruby` it by default download binary version regardless the ABI I'm using right now.

That is normal RubyGems and Bundler behavior, it will always prefer the binary version over the non-binary (Ruby) one.

> So the actual question is, how to resolve this problem? Is it even possible to have separate packages on rubygems that compiled against different ABI? I can see it in gem's metadata, then why it does not use this information during install and does not allow to upload multiple versions of binaries.

Possible options:

1. Propose to RubyGems and rubygems.org to use `ruby_version` as ABI on the packaged gem to construct the gem information. Unsure what would be the timeline on getting that implemented, as this also impacts how Bundler works.
2. Use the fat-binary approach, as described before but for your platform. This might require changes to the gem itself.
3. Compile and host your own binary versions, but that depends on your use case.

Hope this response helps and let me know if you have more questions.

Cheers.

**Comment by avsej** [comment]
Thanks for response. I haven't thought about option 3. Actually it might make sense and definitely worth to try.

**Comment by fauno** [comment]
Sorry to bump this, I was just about to post something similar.  I don't intend to push binary gems to rubygems, but I'm using gem-compiler to keep our own binary gem repository, so our containers don't have to include build tools or build them everytime their Gemfile changes.  The issues I'm facing are:

* There's an [issue on rubygems](https://github.com/rubygems/rubygems/issues/3174) and/or bundler where I can't host binary gems for two libc.  Gems for containers are build with musl but for development they're build with glibc.  Bundler will prefer the musl versions over glibc, breaking development envs.  I still can't figure out what's happening (someday!)

* When upgrading Ruby versions every gem needs to be rebuilt of course, but this prevents us from keeping some projects on earlier Ruby versions until they can be upgraded, so the same issue @avsej was presenting here...

So I was just going to ask what could be the best way to host binary gems for different ABIs and libc's on the same repository :D

**Comment by luislavena** [comment]
Hello @fauno, thank you for your patience, your comment on this issue dropped from my inbox 🤦🏽‍♂️ 

For example, I'm using a custom method to host different ABIs gems and does not use Gemstash or RubyGems, but simply nginx and multiple directories tricks.

Both RubyGems `gem install` and Bundler will include Ruby version information on the HTTP request performed against the server [1](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/request.rb#L270-L287) [2](https://github.com/rubygems/rubygems/blob/master/bundler/lib/bundler/fetcher.rb#L170-L203)

I use that information to determine the version of Ruby that wants to be used and then adjust the root directory of my _gem repository_ to the specific ABI.

When I say _gem repository_, I'm not talking about a Gemstash/RubyGems managed directory, but a simple `gems` directory with the binary gems that has been simply indexed with `gem generate_index` and served statically.

Of course, that doesn't solve the different platform issue you described, but that is a topic for another conversation 😉 

Cheers.
❤️ ❤️ ❤️
